### ISSUE TITLE
Odd gap in response matrix

### ISSUE THREAD

**Issue by AndrewEdmonds11** [alcap-org/g4sim#52]
So I'm running a MC run where I generate protons based on the muon stopping distribution and when I create the response matrix I get this odd gap between the diagonal and the rest of the plot (this wasn't there a week or so ago):

![sir_resonsematrix_oddgap](https://cloud.githubusercontent.com/assets/1848575/5644871/252bfc8a-9660-11e4-8eb2-51edc5c055a1.png)

I think is somewhat related to issue #51 so I've tried the following things:
 - change tres from -1 to 1e10 ns
 - corrected the logic in the hit merging to what Chen intended
 - copied Ben's code from issue #51 to replace that part

None have worked...

I don't think it's a problem with my script that creates the response matrix so I'm just wondering if anyone else has seen this or have any ideas about the cause might be?

**Comment by AndrewEdmonds11** [comment]
Thanks, guys. This is somewhat the road I ended up going down. If I look at left and right response matrices, there is a much "sharper" diagonal on the left hand side which makes sense since muons stop on the front face:

Left:
![sil_resonsematrix_oddgap](https://cloud.githubusercontent.com/assets/1848575/5646596/0753a238-9676-11e4-9583-5821111a04d8.png)

Right:
![sir_resonsematrix_oddgap](https://cloud.githubusercontent.com/assets/1848575/5646603/21be501e-9676-11e4-8dd0-9a15c4e225b4.png)

In addition, while debugging I see protons that have the exact same momentum components in the thin Si as they had initially.

I'm getting the starting positions for these protons from the muon stopping positions of a previous run. Local z looks like this and we can see the peak on the front face (Hang on, is it local positions I should be using...?):
![stopping_localz_explainoddgap](https://cloud.githubusercontent.com/assets/1848575/5646670/b4ddcfbe-9676-11e4-8c0c-a636b30bfd7c.png)

Maybe the MC isn't transporting the proton through the target and depositing energy if it's really close the face of the target... I'll have a look in this direction.

Does no-one else see this then?

**Comment by benkrikler** [comment]
The histo mode I added for primary input assumes you're giving the histrogram in global coordinates.  If you're loading in a histogram that contains local coordinates of muons within the target, then this will be used centred on the global origin.  I think the global origin happens to be the target position (or near to it), right?  But the coordinate system is definitely rotated, so many or even most of the protons will be outside of the target.  Could this be it?

**Comment by AndrewEdmonds11** [comment]
Yep, I just saw that in the code and I'm running now to check.

**Comment by AndrewEdmonds11** [comment]
Yep, that was the problem. I also had to make my histograms a bit more finely binned but now I get these:
![sil_resonsematrix_oddgap_fixed](https://cloud.githubusercontent.com/assets/1848575/5648466/b5afedae-9686-11e4-8a2e-15e5c680d274.png)
![sir_resonsematrix_oddgap_fixed](https://cloud.githubusercontent.com/assets/1848575/5648469/b91f006a-9686-11e4-804a-989e19050bc4.png)

Problem solved :)

**Comment by benkrikler** [comment]
Great!  And there's also no entries with E_observed > E_target.  Is this with the code from #51?

**Comment by AndrewEdmonds11** [comment]
Yep :)
